"""init

Revision ID: 50f225e84342
Revises:
Create Date: 2026-07-16 10:35:28.419486

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "50f225e84342"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
